### ISSUE TITLE
Can't use thdwb as a Go library

### ISSUE THREAD

**Issue by Geo25rey** [danfragoso/thdwb#18]
By moving your code to the root of the repo, other developers can import your code as a module by simply adding `import https://github.com/danfragoso/thdwb` to their code. To decrease clutter, you can have a main directory and put all your files in your main package in it.

Edit: Also, in the `go.mod` file the module name needs to be "github.com/danfragoso/thdwb"
Edit 2: I just noticed that you have other mustard and ketchup repos on GitHub. Perhaps you can do the same thing for them instead of hosting multiple projects in this one.

**Comment by danfragoso** [comment]
Hi @Geo25rey thanks for taking the time to look at this project, this project is not really meant to be a library. The packages in this repo are tightly integrated with each other, if you need some code from this project feel free to just copy it and it's license file.

**Comment by Geo25rey** [comment]
@danfragoso I understand that your project isn't necessarily meant to be a library, but it would be nice if your repo conformed to the typical Go module structure, even if you don't want to move some of your packages like mustard back into their respective repos. Although, I don't think it's a good idea to maintain a copy of gg within this repo.

For some context of why I'm asking for this, I would like to render webpages in my Fyne GUI client for my decentralized mail protocol.

**Comment by danfragoso** [comment]
@Geo25rey Good luck on your project, feel free make a fork or to copy any code you might need. I will not change how this project is organized.
