### ISSUE TITLE
Assets error when running `make`

### ISSUE THREAD

**Issue by AbhayAysola** [danfragoso/thdwb#27]
```# github.com/danfragoso/thdwb/mustard                                                                                                  ../go/src/github.com/danfragoso/thdwb/mustard/tree.go:18:30: undefined: assets.DownChevron                                             ../go/src/github.com/danfragoso/thdwb/mustard/tree.go:19:31: undefined: assets.RightChevron                                            Makefile:11: recipe for target 'run' failed                                                                                            make: *** [run] Error 2   ```

**Comment by danfragoso** [comment]
Sorry for the delayed answer, can you give more info about the environment where this bug was found?
Operating System, Shell, Make and GO versions?

**Comment by AbhayAysola** [comment]
OS - Ubuntu-18.04 (WSL)
Shell - Bash
Make - 4.1
Go - go1.10.4

**Comment by Nv7-GitHub** [comment]
I'm getting this error too

**Comment by Nv7-GitHub** [comment]
I have the images, but the functions aren't in the assets module.

**Comment by Nv7-GitHub** [comment]
It seems like `bundleAssets` has to run.

**Comment by Nv7-GitHub** [comment]
And it worked (aside from it showing in bottom quarter, that's a HiDPI issue)! I may make a PR converting the assets from the bundler into using Go's `embed` package.

**Comment by Nv7-GitHub** [comment]
Made a PR - https://github.com/danfragoso/thdwb/pull/29
Also, when running `make build`, you won't get this error, I just got it because I used the `go build` command.

**Comment by danfragoso** [comment]
Thanks for taking the time to work on this issue!

**Comment by AbhayAysola** [comment]
Cool!
